name: Big Data Scheduling

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analyze script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_APP: ${{ secrets.DB_APP }}
        run: python analyze.py